version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - "> 5.5.2, < 6"
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - "> 5.5.2, < 6"
  - dependency-name: org.junit.jupiter:junit-jupiter-params
    versions:
    - "> 5.5.2, < 6"
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_227
    - 4.2.0_228
    - 4.2.0_229
    - 4.2.0_236
    - 4.2.0_241
    - 4.2.0_245
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.16
    - 1.18.18
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
