sudo: true

os:
  - linux

language: java
jdk:
  - oraclejdk11

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: mvn clean verify -DfailIfNoTests=true
    - stage: "Coverage"
      name: "Process code coverage"
      script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)